//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Prontuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consulta
    {
        public int id { get; set; }
        public int paciente_id { get; set; }
        public string motivo { get; set; }
        public System.DateTime data_consulta { get; set; }
        public int medico_id { get; set; }
    
        public virtual medico medico { get; set; }
        public virtual paciente paciente { get; set; }
    }
}
