//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Prontuario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepcionista
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string cpf { get; set; }
    }
}
